#!/usr/bin/perl
use HTML::TableExtract;
use Data::Dumper;
use DBI;
use POSIX;
### Db connection 
my $hostname = 'eabu-systest-db.juniper.net';
my $user = "postgres";
my $pass = "postgres";
my $port = "5432";
my $dsn = "dbi:Pg:database=eabu_rod;host=$hostname;port=$port";
my $dbh = DBI->connect($dsn,$user,$pass)
                or die "Couldn't connect to database ".DBI->errstr;
my $db_rm = DBI->connect("dbi:Pg:database=systest_live;host=ttpgdb.juniper.net;port=$port", "ext_ft_dr_gui_rw", 'ext_ft_dr_gui_rw') or die "Could not connect to DB".DBI->errstr;
$csvfile = $ARGV[0];
@lines = `cat $csvfile`;
$id=1;
@missing = ();
foreach $l(@lines)
{
	chomp($l);
	$query = "select test_id,script from script_owner where test_id=$l";

	my $sth=$dbh->prepare($query);
    $sth->execute or "$l not found ";
	my $r=$sth->fetchall_arrayref({}) or "$l not found ";
	$c = @{$r};
	if($c <=0) { push @missing,$l;}
	
	
}
foreach $l(@missing)
{
    $query = "select test_id,cvspath from test where test_id=$l";
    my @res =db_get_all_rows($query);
	print "$res[0]->{test_id}, $res[0]->{cvspath} \n"


}
sub db_get_all_rows {
    my $query = shift;
    my $dbrm = $db_rm->prepare($query);
    $dbrm->execute();
    my $q_out = $dbrm->fetchall_arrayref({});
    $dbrm->finish();
    return @{$q_out};
}
